### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by eliliam** [hmartos/bitbucket-pull-request-auto-delete-branch#4]
I'd love to see this extension come to Firefox, as a good amount of developers use Firefox instead of Chrome. Do you have plans to publish this to the Firefox extension store?

**Comment by CPCoder** [comment]
@eliliam I have ported this extension for Firefox:
https://github.com/SHWorX/bitbucket-pr-auto-delete-source-branch

Firefox extension:
https://addons.mozilla.org/en-US/firefox/addon/bbpradelbr/

**Comment by eliliam** [comment]
Fantastic!! Thanks for porting that!
